apiVersion: apps/v1
kind: Deployment
metadata:
  name: completion-service
spec:
  replicas: 10
  selector:
    matchLabels:
      app: completion-service
  template:
    metadata:
      labels:
        app: completion-service
    spec:
      containers:
        - name: completion-service
          image: stwomack/completion-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: db-secret
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://grafana-k8s-monitoring-alloy.default.svc.cluster.local:4318"